keys:
  - &admin_noguchilin age16gmmun2lx63ruhlu4a60u8v6sda65hrzpny6ykuyy0rhafcnnvaqgdtqrl
  - &host_nixos age1nm3fv55cpggpvgyhcg75xxwu8weew220kae3pz52kzggwgy72apqtxl8t6

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *admin_noguchilin
      - *host_nixos