keys:
  - &admin_noguchilin age1e5qdvxkpw2qwet46gu0jmky2nuqxxsszssj8nwucwpwrqsfcuefqu32ech
  - &host_nixos age1nm3fv55cpggpvgyhcg75xxwu8weew220kae3pz52kzggwgy72apqtxl8t6

creation_rules:
  - path_regex: .*\.yaml$
    key_groups:
    - age:
      - *admin_noguchilin
      - *host_nixos
