keys:
  - &admin_home_lab_01 age1nm3fv55cpggpvgyhcg75xxwu8weew220kae3pz52kzggwgy72apqtxl8t6

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_home_lab_01
